version: 2
updates:
  # Maintain dependencies for GitHub Actions
  # src: https://github.com/marketplace/actions/build-and-push-docker-images#keep-up-to-date-with-github-dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Also keep Docker (Helm) dependencies up-to-date
  # see: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
